# Generated by Django 6.0.7 on 2026-07-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_number', models.CharField(max_length=100, unique=True, verbose_name='የደብዳቤ ቁጥር')),
                ('sender', models.CharField(max_length=200, verbose_name='ላኪ (መስሪያ ቤት)')),
                ('subject', models.CharField(max_length=300, verbose_name='ጉዳዩ')),
                ('received_date', models.DateField(auto_now_add=True, verbose_name='የመጣበት ቀን')),
                ('assigned_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='የተመራለት ሰው/ክፍል')),
                ('status', models.CharField(choices=[('PENDING', 'በሂደት ላይ'), ('ASSIGNED', 'የተመራ'), ('COMPLETED', 'የተጠናቀቀ')], default='PENDING', max_length=20, verbose_name='ደረጃ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ማብራሪያ')),
            ],
        ),
    ]
