# Generated by Django 6.0.7 on 2026-07-15 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='assign_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ደብዳቤው የተመራበት ቀን'),
        ),
        migrations.AddField(
            model_name='letter',
            name='assigned_by',
            field=models.CharField(default='ያልተገለጸ', max_length=255, verbose_name='ደብዳቤውን የመራው ኃላፊ'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='assigned_to',
            field=models.CharField(default='temp', max_length=255, verbose_name='የተመራለት ሰው/ክፍል'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_number',
            field=models.CharField(max_length=100, verbose_name='የደብዳቤ ቁጥር'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='received_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ደብዳቤው የገባበት ቀን'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='sender',
            field=models.CharField(max_length=255, verbose_name='ላኪ (መሥሪያ ቤት)'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='status',
            field=models.CharField(choices=[('new', 'አዲስ'), ('in_progress', 'በሂደት ላይ'), ('completed', 'ተጠናቋል')], default='new', max_length=20, verbose_name='ደረጃ'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='ጉዳይ/ርዕስ'),
        ),
    ]
