# Generated by Django 6.0.7 on 2026-07-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_assign_date_letter_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='scanned_copy',
            field=models.FileField(blank=True, null=True, upload_to='scanned_letters/'),
        ),
    ]
